services:
  - type: web
    name: skill-orbit-india
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://skillorbitindiadb_aqyk_user:R2vb7eFCXYkOC7EKEDkTX5N136gtwOao@dpg-daa51htg1s2s73c5pb7g-a/skill_orbit_india
